"""empty message

Revision ID: 297383c812c7
Revises: 
Create Date: 2022-11-25 15:02:50.076849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297383c812c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('supervisor', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ass_supervisor', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['ass_supervisor'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['manager'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['supervisor'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ass_supervisor')
        batch_op.drop_column('supervisor')
        batch_op.drop_column('manager')

    # ### end Alembic commands ###
