"""empty message

Revision ID: 8b2bad0a4da5
Revises: 
Create Date: 2022-12-06 11:23:22.540410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2bad0a4da5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_employee', schema=None) as batch_op:
        batch_op.drop_constraint('shop_employee_shop_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'shop', ['shop_id'], ['id'], ondelete='cascade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('shop_employee_shop_id_fkey', 'shop', ['shop_id'], ['id'])

    # ### end Alembic commands ###
